enum ACTION_TYPES {
    SET_KEY_DOWN_INIT = '@ORTALIOPL@SET_KEY_DOWN_INIT',
    SET_KEY_DOWN_SUCCESS = '@ORTALIOPL@SET_KEY_DOWN_SUCCESS',
    SET_LAYOUT_OPTIONS= '@ORTALIOPL@SET_LAYOUT_OPTIONS',
    SET_ITEMS_GRAPH = '@ORTALIOPL@SET_ITEMS_GRAPH'
}
export default ACTION_TYPES;